### PR TITLE
Updated build instructions

### LINKED ISSUE #11: 'constexpr' does not name a type
While trying to compile....
In file included from C:\Program Files (x86)\Arduino\hardware\teensy\cores\teensy/Stream.h:24,
                 from C:\Program Files (x86)\Arduino\hardware\teensy\cores\teensy/../usb_serial/usb_api.h:6,
                 from C:\Program Files (x86)\Arduino\hardware\teensy\cores\teensy/usb_api.h:2,
                 from C:\Program Files (x86)\Arduino\hardware\teensy\cores\teensy/WProgram.h:22,
                 from C:\Program Files (x86)\Arduino\hardware\teensy\cores\teensy/Arduino.h:1,
                 from /Marlin.h:30,
                 from BlinkM.cpp:5:
C:\Program Files (x86)\Arduino\hardware\teensy\cores\teensy/Print.h:46: error: 'constexpr' does not name a type

### PR DESCRIPTION
**Pull request by kapaw**
There are some incompatibilities between different versions of Arduino, Teensyduino and this fork of Marlin. I managed to get this fork to compile using Arduino 1.0.6, Teensyduino 1.36 and by removing the UTF-8 BOM introduced in https://github.com/QU-BD/Up-Marlin/commit/428704869d5b0e49f8e450e71f3767b14dbc1b4c.

This should also fix #11.

### CODE REVIEW

**Comment by KeithJRome** [comment]
LGTM, thanks!
